name:                websuck1t
version:             0.1.0.0
github:              "ilyakooo0/websuck1t"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/foo#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- servant
- warp
- containers
- text
- aeson
- mtl
- servant-docs
- servant-swagger
- swagger2
- bytestring
- servant-client
- http-client
- http-client-tls
- stm
- random
# - conduit
- servant-websockets
- websockets
- lens

library:
  source-dirs: src

executables:
  websuck1t-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - websuck1t
  docs-exe:
    main:                Docs.hs
    source-dirs:         docs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - websuck1t
  swagger-exe:
    main:                Swagger.hs
    source-dirs:         swagger
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - websuck1t

tests:
  foo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - websuck1t
